import Header from "@/components/Universal/Header/Header";
import "./globals.css";
import StyledComponentsRegistry from "../lib/registry";

export const metadata = {
    title: "Ermin Mushic | Strategic Partner",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html suppressHydrationWarning={true} lang="en">
            <head>
                <link rel="icon" href="/images/PLogo.webp" sizes="32x32" />
            </head>
            <StyledComponentsRegistry>
                <body suppressHydrationWarning={true}>
                    <header>
                        <Header />
                    </header>
                    {children}
                    <footer></footer>
                </body>
            </StyledComponentsRegistry>
        </html>
    );
}
