import Header from "@/components/Universal/Header/Header";
import "./globals.css";
import StyledComponentsRegistry from "../lib/registry";
import Footer from "@/components/Universal/Footer/Footer";
import ScrollToTopButton from "@/components/Universal/ScrollToTopButton/ScrollToTopButton";

export const metadata = {
    title: "Ermin Mushic | Digital marketer",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html suppressHydrationWarning={true} lang="en">
            <head>
                <link rel="icon" href="/images/PLogo.webp" sizes="32x32" />
            </head>
            <StyledComponentsRegistry>
                <body suppressHydrationWarning={true}>
                    <header>
                        <Header />
                    </header>
                    {children}
                    <ScrollToTopButton />
                    <footer>
                        <Footer />
                    </footer>
                </body>
            </StyledComponentsRegistry>
        </html>
    );
}
